### ISSUE TITLE
Winner = draw?

### ISSUE THREAD

**Issue by dave-cross** [marianoheller/tic-tac-toe-minimax#1]
This is so great! You've just saved me a bunch of time.

Feature request: When the game is a draw, indicate that in the `winner` property. Possibly let the app (in my case VueJS) reset the board instead.

```
winner: ("huPlayer" | "aiPlayer" | "draw" | null)
```

Still fantastic and I'm using it right now . For now, I'll test to see if the board was reset, but I think this could be a nice touch.

Cheers,

-Dave

**Comment by marianoheller** [comment]
Thanks!
Sure, I'll look into that.

**Comment by marianoheller** [comment]
Ok, should be done.

Changes: 
1) Draw `winner`  added.
`winner: ("huPlayer" | "aiPlayer" | "draw" | null)`
2) If a winning | draw condition is reached or provided on input, the returned board will be the same (no resetting) and `winner` prop will reflect the result of the game.

**Comment by dave-cross** [comment]
That works! I did have to go in and run your build script, but after that, worked like a charm.

Thanks for the quick turnaround.

-Dave

**Comment by marianoheller** [comment]
Whoops! Forgot about that :D
Fixed & closed.
